### ISSUE TITLE
Quickstart etc instructions not working

### ISSUE THREAD

**Issue by rub1e** [fac-freelancers/website#54]
- Your clone thing is pointing to the old repo
- Quickstart - `open index.html` isn't working on either of my ubuntu 12.04 or 14.04 systems
- Same with the `build.sh` - I only managed to get it working using `harp server _harp`

**Comment by samhstn** [comment]
Clone pointing to the wrong repo changed by commit #60 

What happens when you run: `open index.html`, you have to have that file in your current working directory for that to work. It will be there after harp has compiled.
If that fails maybe try just opening the file by clicking open

For the build script you have to run `./build.sh` not `build.sh`

**Comment by samhstn** [comment]
Thanks for pointing out the typo, let me know if you still are having problems with running the build script
